### ISSUE TITLE
Using protobuf-src when a dependency depends on protobuf

### ISSUE THREAD

**Issue by shhivv** [MaterializeInc/rust-protobuf-native#19]
Hello,

I am trying to make a Tauri app and one of my dependencies is the `lancedb` crate - this crate depends on prost during build time.

When I try to build the app, I get an error that protobuf doesn't exist and the env var `PROTOC` is not set. 

How can I use this crate so that that prost which is a dependency of a dependency during build time can access protobuf binaries?

I've tried adding the  protobuf-src crate to my `Cargo.toml` and setting the env var in my build.rs but it doesn't work because the lancdb crate gets compiled before my binary.

Thank you

**Comment by benesch** [comment]
You have two options.

Option 1 is to write a shell script that invokes `cargo build` on `protobuf_src`, sets `PROTOC` to the location of the built `protoc` binary, and then invokes `cargo build` again to build your project.

Option 2 is to make a PR to the `lancedb` project that adds an optional `protoc-vendored` feature that, when enabled, introduces a build-time dependency on this crate, then sets `PROTOC` to the location of the built `protoc` binary when building `lancedb`. Then you can enable that feature in your downstream project.

**Comment by shhivv** [comment]
Thank you for the response. Can you please brief me on how I would go about the first option.

**Comment by benesch** [comment]
So sorry, but that's beyond the kind of support we can provide here. This issue tracker is for bugs and feature requests about these crates, not general purpose help orchestrating builds of Rust projects. I suggest you try asking on one of the general purpose Rust forums, like https://users.rust-lang.org/c/help/5.

**Comment by shhivv** [comment]
Got it thank you
